# ===== Тестовые данные для логина/профиля =====
# файл в UTF-8

# Базовый адрес стенда/прода (можно переопределить -Dbase.url=...)
base.url=https://pikabu.ru

# Валидный пользователь (generic)
user.valid.username=wertygjh
user.valid.email=rd.galiuliln@gmail.com
user.valid.password=bAsry8-gangek-mevkob

user.login.email=rd.galiuliln@gmail.com
user.login.password=bAsry8-gangek-mevkob

# Невалидные данные (для негативных проверок)
user.invalid.username=ab
user.invalid.email=invalid-email
user.invalid.password=12345

# Технические настройки (можно переопределять через -D)
browser=chrome
page.load.timeout.seconds=300
implicit.wait.ms=0
explicit.wait.seconds=10

-Dbase.url=https://pikabu.ru
-Duser.valid.email=rd.galiuliln@gmail.com
-Duser.valid.password=bAsry8-gangek-mevkob
-Dexplicit.wait.seconds=20