CREATE TABLE USERS (
                       ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       LOGIN VARCHAR2(50) UNIQUE NOT NULL,
                       PASSWORD_HASH VARCHAR2(64) NOT NULL
);

CREATE TABLE POINT_RESULTS (
                               ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               X_VALUE NUMBER(10,4) NOT NULL,
                               Y_VALUE NUMBER(10,4) NOT NULL,
                               R_VALUE NUMBER(10,4) NOT NULL,
                               HIT CHAR(1) CHECK (HIT IN ('Y','N')) NOT NULL,
                               TIMESTAMP_CREATED TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                               USER_ID NUMBER NOT NULL,
                               CONSTRAINT FK_POINT_USER FOREIGN KEY (USER_ID)
                                   REFERENCES USERS(ID)
);